apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(PROJECT_IN_NAME)
spec:
  template:
    spec:
      containers:
        - name: $(PROJECT)
          image: $(IMAGE_PATH):latest
          ports:
            - name: tcp-mysql
              containerPort: 3306
            - $patch: delete
              containerPort: 8080
          livenessProbe:
          readinessProbe:
