apiVersion: v1
kind: Service
metadata:
  name: $(PROJECT_IN_NAME)
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: tcp-mysql
    - $patch: delete
      port: 8080
